export const awsServiceTableRows = {
  EC2: [
    {
      id: "1",
      resourceId: "i-0a12bc34d567ef001",
      name: "web-server-1",
      status: "running",
      region: "ap-south-1",
    },
    {
      id: "2",
      resourceId: "i-0a12bc34d567ef002",
      name: "backend-api",
      status: "stopped",
      region: "us-east-1",
    },
    {
      id: "3",
      resourceId: "i-0a12bc34d567ef003",
      name: "auth-service",
      status: "running",
      region: "eu-west-1",
    },
    {
      id: "4",
      resourceId: "i-0a12bc34d567ef004",
      name: "cron-worker",
      status: "running",
      region: "ap-south-1",
    },
    {
      id: "5",
      resourceId: "i-0a12bc34d567ef005",
      name: "analytics-node",
      status: "stopped",
      region: "us-west-2",
    },
  ],

  ASG: [
    {
      id: "1",
      resourceId: "asg-web-asg",
      name: "web-asg",
      desired: 3,
      min: 1,
      max: 5,
      status: "active",
      region: "ap-south-1",
    },
    {
      id: "2",
      resourceId: "asg-api-asg",
      name: "api-asg",
      desired: 4,
      min: 2,
      max: 6,
      status: "active",
      region: "us-east-1",
    },
    {
      id: "3",
      resourceId: "asg-batch-asg",
      name: "batch-asg",
      desired: 1,
      min: 0,
      max: 3,
      status: "active",
      region: "eu-west-1",
    },
    {
      id: "4",
      resourceId: "asg-worker-asg",
      name: "worker-asg",
      desired: 2,
      min: 1,
      max: 4,
      status: "active",
      region: "ap-south-1",
    },
    {
      id: "5",
      resourceId: "asg-cron-asg",
      name: "cron-asg",
      desired: 1,
      min: 0,
      max: 2,
      status: "active",
      region: "us-west-2",
    },
  ],

  RDS: [
    {
      id: "1",
      resourceId: "rds-user-db",
      name: "user-db",
      engine: "MySQL",
      status: "available",
      region: "ap-south-1",
    },
    {
      id: "2",
      resourceId: "rds-order-db",
      name: "order-db",
      engine: "PostgreSQL",
      status: "stopped",
      region: "us-east-1",
    },
    {
      id: "3",
      resourceId: "rds-auth-db",
      name: "auth-db",
      engine: "MySQL",
      status: "available",
      region: "eu-west-1",
    },
    {
      id: "4",
      resourceId: "rds-analytics-db",
      name: "analytics-db",
      engine: "Aurora",
      status: "available",
      region: "us-west-2",
    },
    {
      id: "5",
      resourceId: "rds-logs-db",
      name: "logs-db",
      engine: "PostgreSQL",
      status: "stopped",
      region: "ap-south-1",
    },
  ],
};
